--SET @db_name = ?;
SET @table_name = 'first_table';

SELECT
  GROUP_CONCAT(
    COLUMN_NAME,
    UPPER(DATA_TYPE),
    IF(IS_NULLABLE = 'YES', 'NULL', 'NOTNULL'),
    IF(EXTRA = 'auto_increment', 'AUTO_INCREMENT', ''),
    IF(COLUMN_DEFAULT IS NOT NULL, CONCAT('DEFAULT', COLUMN_DEFAULT), '')
    ORDER BY ORDINAL_POSITION SEPARATOR ',\n'
  ) AS table_description
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = @db_name
  AND TABLE_NAME = @table_name;
