--SET @table_name = 'first_table';
SET @database_name = 'hbtn_0c_0';

SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY ORDINAL_POSITION) AS ColumnNames
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @table_name AND TABLE_SCHEMA = @database_name;

SELECT GROUP_CONCAT(COLUMN_TYPE ORDER BY ORDINAL_POSITION) AS ColumnTypes
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @table_name AND TABLE_SCHEMA = @database_name;

SELECT GROUP_CONCAT(IS_NULLABLE ORDER BY ORDINAL_POSITION) AS IsNullable
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @table_name AND TABLE_SCHEMA = @database_name;

SELECT GROUP_CONCAT(COLUMN_KEY ORDER BY ORDINAL_POSITION) AS ColumnKeys
